### ISSUE TITLE
数据库缺失

### ISSUE THREAD

**Issue by w391457094** [aishang2015/Yu#9]
可以提供数据库吗？你的登录还涉及到目录权限，没有的话改起来比较麻烦，我的qq邮箱391457094@qq.com, 可以提供一下吗，谢谢

**Comment by aishang2015** [comment]
请查看重构版的https://github.com/aishang2015/Convenience,数据初始化在DbContextSeed中。
这一版数据初始化在DatabaseSeed.cs类中

**Comment by w391457094** [comment]
多谢老哥，已解决，这个做法太赞了
